### ISSUE TITLE
Banner not seen on markbot

### ISSUE THREAD

**Issue by SridharShrinidhi** [SridharShrinidhi/leafy-decorations#1]
@hellachella The screenshots on markbot show a huge difference because the banner is different on markbot. 
<img width="522" alt="screen shot 2017-09-30 at 5 14 31 pm" src="https://user-images.githubusercontent.com/22351855/31051832-eb8528b4-a640-11e7-972c-6834e37e8492.png">
<img width="298" alt="screen shot 2017-09-30 at 5 14 53 pm" src="https://user-images.githubusercontent.com/22351855/31051831-eb83e210-a640-11e7-92b3-0809dacc621d.png">
<img width="362" alt="screen shot 2017-09-30 at 5 15 12 pm" src="https://user-images.githubusercontent.com/22351855/31051833-eb958d08-a640-11e7-8925-7dd407a2b423.png">

**Comment by hellachella** [comment]
Hi @SridharShrinidhi 

Try removing the `background-attachment: fixed` property, and try some different arrangements of `background-position:`.

C

**Comment by SridharShrinidhi** [comment]
I removed background-attachment and it worked! @hellachella Thanks!
